AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with API Gateway HTTP endpoint

Resources:

  ApiLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ApiLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  HelloLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HttpTriggerLambda
      Runtime: python3.9
      Handler: index.handler
      Role: !GetAtt ApiLambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def handler(event, context):
              return {
                  'statusCode': 200,
                  'headers': {'Content-Type': 'application/json'},
                  'body': '{"message": "Lambda triggered from API Gateway!"}'
              }

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: HttpApiGateway
      ProtocolType: HTTP

  HttpApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloLambda.Arn}/invocations
      PayloadFormatVersion: "2.0"

  HttpApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: GET /trigger
      Target: !Join 
        - /
        - - integrations
          - !Ref HttpApiIntegration

  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: prod
      AutoDeploy: true

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref HelloLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/GET/trigger

Outputs:
  ApiInvokeURL:
    Description: URL to invoke the Lambda through API Gateway
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod/trigger
